//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServUOControlUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class ServUOInfo : global::System.Configuration.ApplicationSettingsBase {
        
        private static ServUOInfo defaultInstance = ((ServUOInfo)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ServUOInfo())));
        
        public static ServUOInfo Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServUODir {
            get {
                return ((string)(this["ServUODir"]));
            }
            set {
                this["ServUODir"] = value;
            }
        }
    }
}
